config/routes.rb
Rails.application.routes.draw do

  get 'page/new'
  get '/search' => 'pages#search', :as => 'search_page'
  get 'session/new'
  root to: "page#home"

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :airplanes
  resources :users
  resources :flights
  resources :reservations

end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane, optional: true
  has_many :reservations
  has_and_belongs_to_many :users, through: :reservations, optional: true

  attribute :airplane_name, :string

  def generate_seat_map
    rows = self.airplane.rows
    cols = self.airplane.cols

    startRow = 21
    columnLabels = ['A','B','C','D','E','F','G','H','J','K','L','M']
    result = []

    rows.times do |row|
      row_data = {}
      row_data[startRow] = []

      cols.times do |col|
        id = row.to_s + '-' + col.to_s
        columnLabel = columnLabels[col]
        status = 'open'
        status = 'closed' if self.seat_is_reserved? id

        row_data[startRow] << {id: id, col: columnLabel, status: status}
      end

      result << row_data
      startRow = startRow + 1
    end

    result
  end

  def seat_is_reserved? id
    reserved = false

    self.reservations.each do |reservation|
      seat_id = reservation.row.to_s + '-' + reservation.cols.to_s
      reserved = true if seat_id == id
    end

    reserved
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flight
  # ///asscoicate to plane through flight????
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_and_belongs_to_many :flights, through: :reservations, optional: true
  has_secure_password
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController

skip_before_action :verify_authenticity_token, raise: false
  before_action :check_for_admin

  def new
    @airplane = Airplane.new
  end

  def create
    headers['Access-Control-Allow-Origin'] = '*'
    airplane = Airplane.create airplane_params
    redirect_to airplanes_path
    # render json: airplane
  end

  def index
    # headers['Access-Control-Allow-Origin'] = '*'
    # render json: Airplane.all
    @airplanes = Airplane.all

  end

  def show
    @airplane = Airplane.find params[:id]
  end

  def edit
    @airplane = Airplane.find params[:id]
  end

  def update
    airplane=Airplane.find params[:id]
    airplane.update airplane_params

  redirect_to airplane_path
  end

  def destroy
  end

  private
  def airplane_params
    params.require(:airplane).permit(:name, :rows, :cols)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

    def fetch_user
      if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
      end
      session[:user_id] = nil unless @current_user.present?
    end

    def check_if_logged_in
      unless @current_user.present?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end

      def check_for_admin
        redirect_to root_path unless @current_user.present? && @current_user.admin?
      end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # before_action :check_for_admin

  def new
    @flights = Flight.new
    @planes = Airplane.all.map{ |plane| [ plane.name, plane.id ] }
  end

  def create
    Flight.create flight_params
    redirect_to flights_path
  end

  def index
    headers['Access-Control-Allow-Origin'] = '*'

    if params[:to] || params[:from]
      flights = Flight.where( to: params[:to], from: params[:from] )

      flights.each { |flight| flight.airplane_name = flight.airplane.name }

      render json: flights
    else
      @flights = Flight.all
    end
  end

  def show
    @flight= Flight.find params[:id]
  end

  def edit
    @flight = Flight.find params[:id]
  end

  def update
    @flight = Flight.find params[:id]
    @flight.update flight_params
    redirect_to flight_path(@flight.id)
  end

  def destroy
  end

  private

  def flight_params
    params.require(:flight).permit(
      :scheduled, :to, :from, :flight_number, :airplane_id
    )
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  skip_before_action :verify_authenticity_token, raise: false

  def new
  end

  def create
    # headers['Access-Control-Allow-Origin'] = '*'
    rowCol = params[:seat_id].split('-')
    reservation = Reservation.create(
      row: rowCol[0],
      cols: rowCol[1],
      user_id: params[:user_id],
      flight_id: params[:flight_id]
    )
    render json: reservation
  end

  def index
    # headers['Access-Control-Allow-Origin'] = '*'

    flight = Flight.find_by flight_number: params[:flight_number]
    seat_map = flight.generate_seat_map

    render json: { seat_map: seat_map, flight: flight }
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
end

def create
  user= User.find_by email: params[:email]
  if user.present? && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to user_path(user.id)
  else
    flash[:error] = "Invalid email or password"
    redirect_to login_path
  end
end

  def destroy
    session[:user_id]=nil
    redirect_to login_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_authenticity_token, raise: false

  def new
    @user = User.new
  end

  def create
    headers['Access-Control-Allow-Origin'] = '*'
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    headers['Access-Control-Allow-Origin'] = '*'
    @users = User.all
    # render json: User.all
  end


  def show
      @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
      :check_for_admin
    end

    def update
      user = User.find params[:id]
      :check_for_admin
      user.update user_params
      redirect_to user_path(user.id)
    end

    def destroy
      User.destroy params[:id]
      :check_for_admin
      redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :admin, :password_confirmation)
  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/airplanes/_form.html.erb
<%= form_with model:@airplane, local:true, html: {multipart: true}  do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :rows %>
<%= f.text_field :rows %>

<%= f.label :cols %>
<%= f.text_field :cols %>
<%= f.submit id:'submit_button'%>
<%end %>

app/views/airplanes/edit.html.erb
<h1>Edit Airplane: <%= @airplane.name %></h1>
<%= render partial: 'form' %>

app/views/airplanes/index.html.erb
<h1>Airplanes</h1>
<div class='airplane'>
  <% @airplanes.each do |airplane| %>
  <span>
    <%= link_to airplane.name, airplane_path(airplane.id) %>
  </span>
  <% end %>
  <div>
    <%= link_to "Add a Plane ", new_airplane_path, class:"button"  %>
  </div>
</div>

app/views/airplanes/new.html.erb
<h1>Add a Plane</h1>
<%= render partial: 'form' %>

app/views/airplanes/show.html.erb
<h1>#<%= @airplane.id %> ~ <%= @airplane.name %> </h1>

<ul>
  <li>Number of Rows -
    <%= @airplane.rows %> |
  </li>
  <li>Number of Columns -
    <%= @airplane.cols %> |
  </li>
  <li>Total Seats -
    <%= @airplane.rows * @airplane.cols %>
  </li>


</ul>

<ul>
  <% x= 0 %>


<% while x < @airplane.rows %>
  <div class='rows'>Row:<%= x+1 %></div>
  <% y= 0 %>
<% while y < @airplane.cols %>
  <div class='cols'>Seat:<%=y+1%></div>
  <% y = y+1 %>
<% end %>

  <% x = x+1 %>
<% end %>
</ul>

<br>
<% if @current_user.admin == true%>

<%= link_to "Edit this Airplane", edit_airplane_path(@airplane.id), class:"button" %>
<%= link_to "Delete this Airplane", airplane_path(@airplane.id), method: 'delete', class:"button" %>
<% end %>
<br>
<%= link_to "Go back to All Airplanes", airplanes_path, class:"button" %>

app/views/flights/_form.html.erb
<%= form_with model:@flight, local:true do |f| %>

<%= f.label :scheduled %>
<%= f.text_field :scheduled %>

<%= f.label :to %>
<%= f.text_field :to %>

<%= f.label :from %>
<%= f.text_field :from %>

<%= f.label :flight_id %>
<%= f.text_field :flight_id %>

<%= f.label :plane_id %>
<%= f.text_field :plane_id %>



<%= f.submit %>
<%end %>

app/views/flights/edit.html.erb
<h1>Edit a Flight: <%= @flight.flight_id %></h1>
<%= render partial: 'form' %>

app/views/flights/index.html.erb
<h1>Flights</h1>

  <% @flights.each do |flight| %>
  <ul>
    <li>
      Date: <%= flight.scheduled %>
    </li>
    |
    <li>
      <a href="http://localhost:3001/#/flights/<%= flight.flight_number %>" target="_blank">
        Flight: <%= flight.flight_number %>
      </a>
    </li>
    |
    <li>
      <%= flight.from %> to <%= flight.to %>
    </li>
    |
    <li>
      Airplane: <%= flight.airplane.name %>
    </li>
    |
    <li>
      Open Seats: <%= flight.airplane.rows * flight.airplane.cols - flight.reservations.count %> of <%= flight.airplane.rows * flight.airplane.cols %>
    </li>
  </ul>
  <% end %>


<%=link_to "Add a Flight", new_flight_path, class:"button" %>

app/views/flights/new.html.erb
<div class="flight-wrapper">
  <%= form_with model: @flights, local: true do |f| %>
    <%= f.label :flight_number, "Flight #:" %>
    <%= f.text_field :flight_number %>
    <br/>
    <%= f.label :scheduled, "Date:" %>
    <%= f.date_field :scheduled %>
    <br/>
    <%= f.label :to, "Arrival:" %>
    <%= f.text_field :to %>
    <br/>
    <%= f.label :from, "Departure:" %>
    <%= f.text_field :from %>
    <br/>
    <%= f.label :airplane_id, "Plane:" %>
    <%= select(:flight, :airplane_id, options_for_select(@planes)) %>

    <br/>
    <%= f.submit "Create Flight", class:"button" %>
  <% end %>
</div>

<%= link_to "Go back to All Flights", flights_path, class:"button" %>

app/views/flights/show.html.erb
<h1><%= @flight.id %>) <%= @flight.flight_id %> </h1>

<ul>
  <li>Scheduled date of departure-
    <%= @flight.scheduled %>
  </li>
  <li>To-
    <%= @flight.to %>
  </li>
  <li>From-
    <%= @flight.from %>
  </li>
  <li>Plane-
    
    <%=@flight.airplane.name %>

  </li>
  <li>Number of seats availble-
    <%=%>
  </li>
</ul>



<br>
<% if :check_for_admin == true%>

<%= link_to "Edit this Flight", edit_flight_path(@flight.id) %>
<%= link_to "Delete this Flight", flight_path(@flight.id), method: 'delete' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBurningAirlines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div>
    <% if @current_user.present? %>
      Welcome,<%=@current_user.name%>
      <%end %>
    </div>
    <nav>

      <% if @current_user.present? %>

        <ul>
          <li>
            | <%= link_to 'Logout', login_path, method:'delete', class: 'log' %>
          </li>
        | <li>
          <%= link_to 'Home', user_path(@current_user.id), class: 'log' %> |
          </li>

        </ul>
        <% else %>
        <div class='log'>
        <%= link_to 'Login', login_path, class: 'log' %>
        </div>

      <% end %>

    <%= yield %>
  </body>
</html>

app/views/page/home.html.erb
<h1> Burning Airlines </h1>

<div>
  <%= link_to "Airplanes", airplanes_path  %>
</div>
<div>
  <%= link_to "Flights", flights_path  %>
</div>
<div>
  Reservations
</div>
<div>
  Users
</div>

app/views/page/new.html.erb
<h1>Page#new</h1>
<p>Find me in app/views/page/new.html.erb</p>

app/views/reservations/_form.html.erb
<%= form_with model:@reservations, local:true do |f| %>

<%= f.label :row %>
<%= f.text_field :row %>

<%= f.label :cols %>
<%= f.text_field :cols %>

<%= f.label :user_id %>
<%= f.text_field :user_id %>

<%= f.label :flight_id %>
<%= f.text_field :flight_id %>




<%= f.submit %>
<%end %>

app/views/reservations/edit.html.erb
<h1>Edit a Reservation: <%= @reservation.id %></h1>
<%= render partial: 'form' %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<ul class='reservations'>
  <% @reservations.each do |r| %>
  <li>
    <%= link_to r.id, reservation_path(f.id)%>
  </li>
  <% end %>

</ul>

<% if @current_user.present? %>
<% end >
<%= link_to "Add a Reservation ", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>Make a Reservation:</h1>
<%= render partial: 'form' %>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/session/new.html.erb
<div class='login'>
  <h1 class="top-links login">Login</h1>
  <% if flash[:error] %>
  <br>
  <strong><%= flash[:error] %></strong>
  <% end %>
  <br>
  <br>

  <%= form_with url: login_path, local:true do |f| %>
  <%= f.label :email, "Email" %>
  <%= f.text_field :email, id: 'login_email'%>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password, id: 'login_password' %>
  <br>
  <%= f.submit "Login", id: 'login_button'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Welcome <%= @current_user.name%></h1>
<div class="top-links">
  <% if @current_user.admin == true%>
   | <%= link_to "Airplanes", airplanes_path  %>
   | <%= link_to "Flights", flights_path  %>
   |
  <%end %>
</div>